/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
 */
/*note
 * 1 million = 10 lakhs
 */
void main()
{
  int sum = 2;
  int a = 0;
  int b = 2;
  int c = 0;
  while(true)
  {
    c =( b * 4 ) + a ;
    if(c<4000000)
    {
      sum =sum + c;
    }
    else
    {
      break;
    }
    a=b;b=c;
  }
  print(sum);
}
